version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: grid
      POSTGRES_PASSWORD: grid
      POSTGRES_DB: grid
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://grid:grid@db:5432/grid
