"""Initial migration

Revision ID: a5c7aec974eb
Revises: 
Create Date: 2024-09-12 17:04:12.305120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c7aec974eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruits_vegetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shelf_life', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruits_vegetables_id'), 'fruits_vegetables', ['id'], unique=False)
    op.create_index(op.f('ix_fruits_vegetables_shelf_life'), 'fruits_vegetables', ['shelf_life'], unique=False)
    op.create_table('products',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('other_data', sa.JSON(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shelf_life', sa.Integer(), nullable=True),
    sa.Column('total_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_products_item_id'), 'products', ['item_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('product_transactions',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('shelf_life_remaining', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['products.item_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_product_transactions_transaction_id'), 'product_transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_transactions_transaction_id'), table_name='product_transactions')
    op.drop_table('product_transactions')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_item_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_fruits_vegetables_shelf_life'), table_name='fruits_vegetables')
    op.drop_index(op.f('ix_fruits_vegetables_id'), table_name='fruits_vegetables')
    op.drop_table('fruits_vegetables')
    # ### end Alembic commands ###
